### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Dyason** [Kalaborative/survivio-cheat#1]
It seems they've updated this again.

**Comment by Kalaborative** [comment]
Indeed they did, I'll send a fix.

**Comment by Dyason** [comment]
Thanks, I tried to find if it was updated values but did seem to be. Also you changed the repository, I was using the other one.

**Comment by Kalaborative** [comment]
Fixed, let me know if it works for you now.

**Comment by Dyason** [comment]
That's working fine now thanks. That was quick!
